### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by chuangcai** [hjlin0515/face-detection#1]
您好，感谢您的代码分享！
我在学习过程中，运行发现结果似乎有些问题？一个是detect.py文件的_detectScaledWindow()函数里，if type 进行赋值，是会报错的：ValueError: setting an array element with a sequence.
我在Image.py 的初始化里，加了 if len(self.mat.shape) == 3: self.mat = self.mat[:, :, 1]  可以运行，但是结果识别不出人脸，请问要如何解决呢？
十分感谢！

**Comment by hjlin0515** [comment]
您好，我fix了代码里面的一些问题，并测试了一下，您可以重新下载代码再试试。谢谢

**Comment by chuangcai** [comment]
> 您好，我fix了代码里面的一些问题，并测试了一下，您可以重新下载代码再试试。谢谢

您好，这是我用别的图片测试的结果，似乎并不正确。（另外想请问怎么测试png格式的图片呢？）
![微信截图_20190526181801](https://user-images.githubusercontent.com/25891536/58380373-eacab380-7fe2-11e9-9049-03edd24e063f.png)

**Comment by hjlin0515** [comment]
您好，是否可以尝试使用opencv等将图片转成灰度图，而不是直接取第一个通道，谢谢。
