### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HussamCheema** [hjlin0515/face-detection#2]
I'm getting this error:
-detection\detector.py", line 192, in _detectScaledWindow
    `scaledWindowsMat[window][dimension] = (pos - neg1 - neg2) / (3 * w * h)`
ValueError: setting an array element with a sequence.

**Comment by missbook520** [comment]
> I'm getting this error:
> -detection\detector.py", line 192, in _detectScaledWindow
> `scaledWindowsMat[window][dimension] = (pos - neg1 - neg2) / (3 * w * h)`
> ValueError: setting an array element with a sequence.

hello , are you finish it ?
